### ISSUE TITLE
i got error: The Survivors resource file was not found program cannot continue 

### ISSUE THREAD

**Issue by babayaga2137** [Charzard4261/DBD-ResourcePackManager#3]
i got error: The Survivors resource file was not found program cannot continue

**Comment by Charzard4261** [comment]
That means the program failed to automatically download the needed files. Sorry about that!
Please download https://github.com/Charzard4261/DBD-ResourcePackManager-Resources/releases/latest (Click on "Source code (zip)") and extract it to "C:\Users\<your username>\AppData\Local\DBD-ResourcePackManager\Resources". Create the Resources folder if it does not exist.

**Comment by babayaga2137** [comment]
still same error :((

niedz., 28 maj 2023 o 17:01 Charzard4261 ***@***.***>
napisał(a):

**Comment by Charzard4261** [comment]
Can you upload a screen shot of your resources folder?

**Comment by babayaga2137** [comment]
ok everything works now i just deleted all files from appdata that
uninstaller didnt delete and everything works fine by now thx for fast
reply :)

niedz., 28 maj 2023 o 17:28 Charzard4261 ***@***.***>
napisał(a):

**Comment by Charzard4261** [comment]
Glad that it's working!
